const ONEMINUTE = 60;
const SHORT_BREAK_DURATION = ONEMINUTE * 5;
const LONG_BREAK_DURATION = 600;
const POMODORO_DURATION = 1500;
const POMODORO = 'Pomodoro';
const SHORT_BREAK = 'Short Break';
const LONG_BREAK = 'Long Break';

export {
  SHORT_BREAK_DURATION,
  LONG_BREAK_DURATION,
  POMODORO_DURATION,
  POMODORO,
  SHORT_BREAK,
  LONG_BREAK,
};
